import { FormEvent, useEffect, useMemo, useState } from "react"

type Product = {
  id: number; name: string; category: string; price: number; old: number; rating: number; reviews: number; image: string; badge?: string
}
type Page = "home"|"shop"|"product"|"wishlist"|"cart"|"checkout"|"success"|"tracking"|"account"|"support"|"review"|"auth"
type Toast = { message: string; type: "success"|"error"|"info" }
type Direction = "A"|"B"|"C"

const IMG = {
  headphones:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=85",
  headphones2:"https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=1200&q=85",
  sneakers:"https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?auto=format&fit=crop&w=1200&q=85",
  skincare:"https://images.unsplash.com/photo-1580870069867-74c57ee1bb07?auto=format&fit=crop&w=1200&q=85",
  coffee:"https://images.unsplash.com/photo-1565452344518-47faca79dc69?auto=format&fit=crop&w=1200&q=85",
  desk:"https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=85",
}
const PRODUCTS: Product[] = [
  {id:1,name:"NOVA Sound Pro",category:"Electronics",price:4999,old:7999,rating:4.6,reviews:1248,image:IMG.headphones,badge:"38% OFF"},
  {id:2,name:"UrbanFlex Everyday Sneakers",category:"Fashion",price:2499,old:4999,rating:4.5,reviews:842,image:IMG.sneakers,badge:"50% OFF"},
  {id:3,name:"GlowLab Skin Care Kit",category:"Beauty",price:1299,old:1799,rating:4.7,reviews:560,image:IMG.skincare,badge:"28% OFF"},
  {id:4,name:"AeroBrew Smart Coffee Maker",category:"Home",price:3999,old:5499,rating:4.4,reviews:331,image:IMG.coffee,badge:"27% OFF"},
  {id:5,name:"SonicAir Studio Headphones",category:"Electronics",price:6499,old:9499,rating:4.8,reviews:729,image:IMG.headphones2,badge:"32% OFF"},
  {id:6,name:"QuietTone 700",category:"Electronics",price:8999,old:12999,rating:4.6,reviews:904,image:IMG.desk,badge:"31% OFF"},
  {id:7,name:"Daily Dew Essentials",category:"Beauty",price:1899,old:2499,rating:4.3,reviews:287,image:IMG.skincare,badge:"24% OFF"},
  {id:8,name:"AeroPress Morning Set",category:"Home",price:2799,old:3999,rating:4.5,reviews:196,image:IMG.coffee,badge:"30% OFF"},
]
const money=(n:number)=>`₹${n.toLocaleString("en-IN")}`
const CATEGORIES=["Electronics","Fashion","Beauty","Home","Sports","Accessories","Daily Essentials"]

function Icon({name,size=20}:{name:string;size?:number}) {
  const p:Record<string,React.ReactNode>={
    search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,heart:<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/>,
    bag:<><path d="M5 8h14l-1 13H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,
    bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,arrow:<><path d="m9 18 6-6-6-6"/></>,
    back:<><path d="m15 18-6-6 6-6"/></>,check:<path d="m5 12 4 4L19 6"/>,star:<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-2.9-5.6 2.9 1.1-6.2L3 9.6l6.2-.9L12 3Z"/>,
    truck:<><path d="M3 6h11v11H3zM14 10h4l3 3v4h-7z"/><circle cx="7" cy="19" r="2"/><circle cx="18" cy="19" r="2"/></>,menu:<><path d="M4 7h16M4 12h16M4 17h16"/></>,
    close:<><path d="m6 6 12 12M18 6 6 18"/></>,filter:<><path d="M4 7h10M18 7h2M4 17h2M10 17h10"/><circle cx="16" cy="7" r="2"/><circle cx="8" cy="17" r="2"/></>,
    eye:<><path d="M2 12s4-6 10-6 10 6 10 6-4 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2"/></>,
  }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg>
}
function Logo(){return <span className="nova-logo"><i>N</i>NOVA</span>}
function Btn({children,onClick,kind="primary",type="button",disabled=false}:{children:React.ReactNode;onClick?:()=>void;kind?:"primary"|"secondary"|"text"|"danger";type?:"button"|"submit";disabled?:boolean}) {
  return <button className={`nova-btn ${kind}`} onClick={onClick} type={type} disabled={disabled}>{children}</button>
}

export default function NovaWebsite(){
  const [page,setPage]=useState<Page>("home"), [selected,setSelected]=useState(PRODUCTS[0])
  const [cart,setCart]=useState<Record<number,number>>({}), [wishlist,setWishlist]=useState<number[]>([2,3])
  const [toast,setToast]=useState<Toast|null>(null), [searchOpen,setSearchOpen]=useState(false), [query,setQuery]=useState("")
  const [menu,setMenu]=useState(false), [mega,setMega]=useState(false), [accountMenu,setAccountMenu]=useState(false), [notificationsOpen,setNotificationsOpen]=useState(false)
  const [notifications,setNotifications]=useState([{id:1,text:"Your NOVA Sound Pro is ready to ship",read:false},{id:2,text:"Price dropped on an item in your wishlist",read:false},{id:3,text:"Weekend edit: up to 50% off",read:true}])
  const [loggedIn,setLoggedIn]=useState(true), [direction,setDirection]=useState<Direction>("B"), [dark,setDark]=useState(false), [orderPlaced,setOrderPlaced]=useState(false)
  const count=Object.values(cart).reduce((a,b)=>a+b,0), unread=notifications.filter(n=>!n.read).length
  const cartProducts=PRODUCTS.filter(p=>cart[p.id]).map(p=>({...p,qty:cart[p.id]}))
  const subtotal=cartProducts.reduce((s,p)=>s+p.price*p.qty,0)
  const notify=(message:string,type:Toast["type"]="success")=>{setToast({message,type});window.setTimeout(()=>setToast(null),2600)}
  const go=(p:Page)=>{setPage(p);setMenu(false);setMega(false);setAccountMenu(false);window.scrollTo({top:0,behavior:"smooth"})}
  const add=(id:number,qty=1)=>{setCart(c=>({...c,[id]:(c[id]||0)+qty}));notify("Added to cart.")}
  const toggleWish=(id:number)=>{const has=wishlist.includes(id);setWishlist(w=>has?w.filter(x=>x!==id):[...w,id]);notify(has?"Removed from wishlist.":"Saved to wishlist.")}
  const openProduct=(p:Product)=>{setSelected(p);go("product")}
  const search=(term=query)=>{if(!term.trim()){notify("Enter a product or category to search.","error");return}setQuery(term);setSearchOpen(false);go("shop")}
  useEffect(()=>{document.documentElement.classList.toggle("nova-dark",dark)},[dark])
  return <div className={`nova-site direction-${direction}`}>
    <Header {...{go,count,unread,setSearchOpen,menu,setMenu,mega,setMega,accountMenu,setAccountMenu,notificationsOpen,setNotificationsOpen,loggedIn,setLoggedIn,notifications,setNotifications,notify}}/>
    {page==="home"&&<Home {...{go,openProduct,add,wishlist,toggleWish,direction,setDirection}}/>}
    {page==="shop"&&<Shop {...{query,setQuery,search,openProduct,add,wishlist,toggleWish}}/>}
    {page==="product"&&<ProductPage product={selected} {...{add,toggleWish,wishlist,go}}/>}
    {page==="wishlist"&&<Wishlist {...{wishlist,toggleWish,add,openProduct,go}}/>}
    {page==="cart"&&<Cart {...{cart,setCart,cartProducts,subtotal,toggleWish,go,notify}}/>}
    {page==="checkout"&&<Checkout {...{cartProducts,subtotal,go,setOrderPlaced,notify}}/>}
    {page==="success"&&<Success {...{go}}/>}
    {page==="tracking"&&<Tracking {...{go}}/>}
    {page==="account"&&<Account {...{go,dark,setDark,orderPlaced,loggedIn,setLoggedIn,notify}}/>}
    {page==="support"&&<Support notify={notify}/>}
    {page==="review"&&<ReviewCenter {...{direction,setDirection,notify,go,add}}/>}
    {page==="auth"&&<Auth {...{setLoggedIn,go,notify}}/>}
    {!["checkout","success","tracking","auth"].includes(page)&&<Footer go={go} notify={notify}/>}
    {searchOpen&&<SearchOverlay {...{query,setQuery,search,setSearchOpen,openProduct}}/>}
    {toast&&<div className={`nova-toast ${toast.type}`}><Icon name={toast.type==="success"?"check":"bell"} size={17}/>{toast.message}</div>}
  </div>
}

function Header(p:any){
  const close=()=>{p.setMega(false);p.setAccountMenu(false);p.setNotificationsOpen(false)}
  return <><div className="top-note">Complimentary delivery above ₹999 <button onClick={()=>p.go("review")}>Stakeholder review center</button></div>
  <header className="nova-header">
    <button className="mobile-menu" onClick={()=>p.setMenu(!p.menu)} aria-label="Menu"><Icon name="menu"/></button>
    <button className="logo-button" onClick={()=>p.go("home")}><Logo/></button>
    <nav className={p.menu?"open":""}>
      <button onClick={()=>{close();p.setMega(!p.mega)}}>Categories <span>⌄</span></button>
      <button onClick={()=>p.go("shop")}>New arrivals</button><button onClick={()=>{p.go("shop")}}>Best sellers</button>
      <button onClick={()=>p.go("shop")} className="sale-link">Offers</button><button onClick={()=>p.go("review")}>Design review</button>
    </nav>
    <button className="header-search" onClick={()=>p.setSearchOpen(true)}><Icon name="search"/><span>Search products and categories</span><kbd>⌘ K</kbd></button>
    <div className="header-actions">
      <button onClick={()=>{close();p.setNotificationsOpen(!p.notificationsOpen)}} aria-label="Notifications"><Icon name="bell"/>{p.unread>0&&<i>{p.unread}</i>}</button>
      <button onClick={()=>p.go("wishlist")} aria-label="Wishlist"><Icon name="heart"/></button>
      <button onClick={()=>{close();p.setAccountMenu(!p.accountMenu)}} aria-label="Account"><Icon name="user"/></button>
      <button onClick={()=>p.go("cart")} aria-label="Cart"><Icon name="bag"/>{p.count>0&&<i>{p.count}</i>}</button>
    </div>
    {p.mega&&<div className="mega-menu"><div><small>SHOP BY CATEGORY</small>{CATEGORIES.map((c:string)=><button key={c} onClick={()=>p.go("shop")}>{c}<Icon name="arrow" size={15}/></button>)}</div><div className="mega-feature"><img src={IMG.headphones2}/><span>THE SOUND EDIT</span><strong>Quiet, beautifully engineered.</strong><button onClick={()=>p.go("shop")}>Explore audio</button></div></div>}
    {p.notificationsOpen&&<div className="popover notification-pop"><div><h3>Notifications</h3><button onClick={()=>p.setNotifications((n:any[])=>n.map(x=>({...x,read:true})))}>Mark all read</button></div>{p.notifications.map((n:any)=><button key={n.id} className={!n.read?"unread":""} onClick={()=>p.setNotifications((all:any[])=>all.map(x=>x.id===n.id?{...x,read:true}:x))}><i/>{n.text}<span>Today</span></button>)}<Btn kind="text" onClick={()=>p.go("account")}>View notification settings</Btn></div>}
    {p.accountMenu&&<div className="popover account-pop"><div><span>AK</span><p><strong>Aanya Kapoor</strong><small>aanya@example.com</small></p></div>{["Profile","Orders","Addresses","Settings"].map(x=><button key={x} onClick={()=>p.go("account")}>{x}<Icon name="arrow" size={14}/></button>)}<button onClick={()=>{p.setLoggedIn(false);p.setAccountMenu(false);p.notify("You have been logged out.","info");p.go("home")}}>{p.loggedIn?"Log out":"Log in"}</button></div>}
  </header></>
}

function Home({go,openProduct,add,wishlist,toggleWish,direction,setDirection}:any){
  const [slide,setSlide]=useState(0)
  const slides=[{tag:"THE SOUND EDIT",title:"Hear every detail.",copy:"Studio-grade sound. Adaptive silence. Forty hours of listening.",image:IMG.headphones2},{tag:"MOVE WITH INTENT",title:"Made for every day.",copy:"Lightweight comfort meets understated design.",image:IMG.sneakers},{tag:"THE HOME EDIT",title:"Better daily rituals.",copy:"Thoughtful objects for a calmer, more considered home.",image:IMG.coffee}]
  const s=slides[slide]
  return <main>
    <section className="hero"><img src={s.image} alt="Featured NOVA collection"/><div className="hero-shade"/><div className="hero-copy"><span>{s.tag}</span><h1>{s.title}</h1><p>{s.copy}</p><div><Btn onClick={()=>go("shop")}>Shop now <Icon name="arrow" size={16}/></Btn><Btn kind="secondary" onClick={()=>go("shop")}>Explore collections</Btn></div></div>
      <button className="hero-prev" onClick={()=>setSlide((slide+2)%3)}>‹</button><button className="hero-next" onClick={()=>setSlide((slide+1)%3)}>›</button><div className="hero-dots">{slides.map((_,i)=><button className={i===slide?"active":""} key={i} onClick={()=>setSlide(i)} aria-label={`Slide ${i+1}`}/>)}</div>
    </section>
    <section className="direction-switch"><div><span>LIVE DESIGN DIRECTION</span><strong>Compare the same store, three ways.</strong></div>{(["A","B","C"] as Direction[]).map(d=><button className={direction===d?"active":""} onClick={()=>{setDirection(d);notifyDirection(d)}} key={d}><i>{d}</i>{d==="A"?"Minimal":d==="B"?"Commerce":"Premium"}</button>)}<button onClick={()=>go("review")}>Open review center <Icon name="arrow"/></button></section>
    <SectionHead eyebrow="EXPLORE NOVA" title="Shop by category" action={()=>go("shop")}/>
    <section className="category-cards">{PRODUCTS.slice(0,4).map((p,i)=><button key={p.category} onClick={()=>go("shop")}><img src={p.image}/><span>0{i+1}</span><div><h3>{p.category}</h3><p>Explore collection</p></div></button>)}</section>
    {direction==="B"&&<section className="flash"><div><span>FLASH SALE</span><h2>Ends tonight.</h2><p>Limited prices across the most wanted NOVA pieces.</p><Btn onClick={()=>go("shop")}>Shop the sale</Btn></div><div className="countdown"><span><b>02</b>Hours</span><i>:</i><span><b>18</b>Minutes</span><i>:</i><span><b>44</b>Seconds</span></div></section>}
    <section className="section-wrap"><SectionHead eyebrow={direction==="A"?"MADE SIMPLE":direction==="B"?"TRENDING NOW":"THE CURATED EDIT"} title="Considered for you" action={()=>go("shop")}/><div className="product-grid">{PRODUCTS.slice(0,4).map(p=><ProductCard key={p.id} product={p} {...{openProduct,add,wishlist,toggleWish}}/>)}</div></section>
    <section className="editorial"><img src={IMG.sneakers}/><div><span>THE EVERYDAY SERIES</span><h2>Made to move.<br/>Styled to stay.</h2><p>Everyday essentials selected for comfort, craft, and a life in motion.</p><Btn kind="secondary" onClick={()=>openProduct(PRODUCTS[1])}>Discover UrbanFlex</Btn></div></section>
    <section className="benefits">{[["truck","Free delivery","On orders above ₹999"],["check","Easy returns","30-day return window"],["star","Genuine products","Quality guaranteed"],["user","Always here","24/7 expert support"]].map(x=><div key={x[1]}><Icon name={x[0]}/><span><strong>{x[1]}</strong>{x[2]}</span></div>)}</section>
  </main>
  function notifyDirection(d:Direction){void d}
}
function SectionHead({eyebrow,title,action}:{eyebrow:string;title:string;action:()=>void}){return <div className="section-head section-wrap"><div><span>{eyebrow}</span><h2>{title}</h2></div><button onClick={action}>View all <Icon name="arrow"/></button></div>}
function ProductCard({product,openProduct,add,wishlist,toggleWish}:any){const saved=wishlist.includes(product.id);return <article className="product-card-web"><button className="product-photo" onClick={()=>openProduct(product)}><img src={product.image}/><span>{product.badge}</span></button><button className={`heart ${saved?"saved":""}`} onClick={()=>toggleWish(product.id)} aria-label="Toggle wishlist"><Icon name="heart"/></button><div className="product-meta"><small>{product.category}</small><span className="stars"><Icon name="star" size={12}/>{product.rating} ({product.reviews})</span><button onClick={()=>openProduct(product)}>{product.name}</button><p><b>{money(product.price)}</b><s>{money(product.old)}</s></p><Btn kind="secondary" onClick={()=>add(product.id)}>Add to cart</Btn></div></article>}

function Shop({query,setQuery,search,openProduct,add,wishlist,toggleWish}:any){
  const [sort,setSort]=useState("relevance"),[category,setCategory]=useState("All"),[minRating,setMinRating]=useState(0),[discount,setDiscount]=useState(0),[filtersOpen,setFiltersOpen]=useState(false),[page,setPage]=useState(1)
  let result=PRODUCTS.filter(p=>(!query||`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()))&&(category==="All"||p.category===category)&&p.rating>=minRating&&Math.round((1-p.price/p.old)*100)>=discount)
  result=[...result].sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:sort==="rating"?b.rating-a.rating:sort==="discount"?(1-b.price/b.old)-(1-a.price/a.old):a.id-b.id)
  const clear=()=>{setCategory("All");setMinRating(0);setDiscount(0);setQuery("")}
  return <main className="shop-page"><div className="shop-title"><span>THE NOVA COLLECTION</span><h1>{query?`Results for “${query}”`:"Objects for better living."}</h1><p>Products selected for how they look, feel, and work in real life.</p><form onSubmit={e=>{e.preventDefault();search()}}><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the collection"/><button type="submit">Search</button></form></div>
    <div className="catalog"><aside className={filtersOpen?"open":""}><div><h3>Filters</h3><button onClick={clear}>Clear all</button></div><label>Category</label>{["All",...CATEGORIES.slice(0,4)].map(c=><button className={category===c?"active":""} onClick={()=>setCategory(c)} key={c}><i/>{c}</button>)}<label>Rating</label>{[4,3].map(n=><button className={minRating===n?"active":""} onClick={()=>setMinRating(n)} key={n}><i/>{n}★ & above</button>)}<label>Discount</label>{[20,30,50].map(n=><button className={discount===n?"active":""} onClick={()=>setDiscount(n)} key={n}><i/>{n}% or more</button>)}</aside>
      <section className="catalog-results"><div className="catalog-bar"><span><b>{result.length}</b> products</span><button className="filter-mobile" onClick={()=>setFiltersOpen(!filtersOpen)}><Icon name="filter"/> Filters</button><select value={sort} onChange={e=>setSort(e.target.value)}><option value="relevance">Sort: Relevance</option><option value="low">Price: Low to high</option><option value="high">Price: High to low</option><option value="rating">Top rated</option><option value="discount">Biggest discount</option></select></div>
      {(category!=="All"||minRating||discount||query)&&<div className="filter-chips">{query&&<button onClick={()=>setQuery("")}>“{query}” ×</button>}{category!=="All"&&<button onClick={()=>setCategory("All")}>{category} ×</button>}{minRating>0&&<button onClick={()=>setMinRating(0)}>{minRating}★ & above ×</button>}{discount>0&&<button onClick={()=>setDiscount(0)}>{discount}%+ ×</button>}</div>}
      {result.length?<div className="product-grid">{result.map(p=><ProductCard key={p.id} product={p} {...{openProduct,add,wishlist,toggleWish}}/>)}</div>:<div className="empty-state"><Icon name="search" size={40}/><h2>No products found</h2><p>Try a different search or browse our popular categories.</p><Btn onClick={clear}>Clear search</Btn></div>}
      {result.length>0&&<div className="pagination"><button disabled={page===1} onClick={()=>setPage(1)}>‹</button>{[1,2,3].map(n=><button className={page===n?"active":""} onClick={()=>setPage(n)} key={n}>{n}</button>)}<button onClick={()=>setPage(Math.min(3,page+1))}>›</button></div>}</section></div></main>
}

function ProductPage({product,add,toggleWish,wishlist,go}:any){
  const [qty,setQty]=useState(1),[color,setColor]=useState("Midnight"),[tab,setTab]=useState("Description"),[pin,setPin]=useState(""),[pinStatus,setPinStatus]=useState(""),[image,setImage]=useState(0),[helpful,setHelpful]=useState(false),[zoom,setZoom]=useState(false)
  const images=[product.image,product.id===1?IMG.headphones2:product.image,product.id===1?IMG.desk:product.image]
  return <main className="detail-page"><div className="breadcrumbs"><button onClick={()=>go("home")}>Home</button><span>/</span><button onClick={()=>go("shop")}>{product.category}</button><span>/</span><b>{product.name}</b></div><div className="detail-layout">
    <div className="gallery"><div className="thumbs">{images.map((x,i)=><button className={image===i?"active":""} onClick={()=>setImage(i)} key={i}><img src={x}/></button>)}</div><button className={`main-image ${zoom?"zoom":""}`} onClick={()=>setZoom(!zoom)}><img src={images[image]}/><span><Icon name="eye"/> Click to zoom</span></button></div>
    <div className="detail-info"><span className="eyebrow">{product.category} · NOVA EXCLUSIVE</span><h1>{product.name}</h1><div className="detail-rating"><b><Icon name="star" size={14}/>{product.rating}</b><button onClick={()=>setTab("Reviews")}>{product.reviews.toLocaleString()} verified reviews</button></div><div className="detail-price"><strong>{money(product.price)}</strong><s>{money(product.old)}</s><em>{product.badge}</em></div><p>Inclusive of all taxes. No-cost EMI available from ₹417/month.</p>
      <div className="detail-option"><label>Colour <b>{color}</b></label><div className="color-options">{["Midnight","Cloud","Ocean"].map((c,i)=><button className={color===c?"active":""} onClick={()=>setColor(c)} key={c}><i className={`swatch s${i}`}/>{c}</button>)}</div></div>
      <div className="detail-option"><label>Quantity</label><div className="quantity"><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><b>{qty}</b><button onClick={()=>setQty(qty+1)}>+</button></div></div>
      <div className="pin-check"><label>Check delivery</label><div><input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="Enter 6-digit PIN"/><button onClick={()=>setPinStatus(pin.length===6?"Delivery available by Tuesday":"Enter a valid 6-digit PIN")}>Check</button></div>{pinStatus&&<span className={pin.length===6?"ok":"bad"}>{pinStatus}</span>}</div>
      <div className="detail-actions"><Btn onClick={()=>add(product.id,qty)}>Add to cart · {money(product.price*qty)}</Btn><Btn kind="secondary" onClick={()=>{add(product.id,qty);go("checkout")}}>Buy now</Btn><button className={wishlist.includes(product.id)?"saved":""} onClick={()=>toggleWish(product.id)}><Icon name="heart"/></button></div>
      <div className="delivery-note"><Icon name="truck"/><span><strong>Free delivery by Tuesday, 18 June</strong>Easy 30-day returns · One-year warranty</span></div>
    </div></div>
    <section className="product-tabs"><div>{["Description","Specifications","Reviews","Shipping","Returns"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><article>{tab==="Description"&&<><h2>Made for immersive everyday listening.</h2><p>NOVA Sound Pro combines adaptive noise cancellation, spatial audio, and considered comfort in a refined over-ear design. Built for commutes, focus sessions, and long-form listening.</p></>}{tab==="Specifications"&&<dl><div><dt>Battery</dt><dd>Up to 40 hours</dd></div><div><dt>Connectivity</dt><dd>Bluetooth 5.3 · USB-C</dd></div><div><dt>Weight</dt><dd>254 grams</dd></div></dl>}{tab==="Reviews"&&<div className="reviews"><div><strong>4.6</strong><span>★★★★★<small>Based on {product.reviews} reviews</small></span></div><article><b>Aarav Mehta</b><span>★★★★★ · 12 June 2025</span><p>Excellent sound detail and the comfort is genuinely good for long work sessions.</p><button className={helpful?"active":""} onClick={()=>setHelpful(!helpful)}>{helpful?"Helpful · 25":"Helpful · 24"}</button></article></div>}{tab==="Shipping"&&<><h2>Fast, trackable delivery.</h2><p>Standard delivery takes 3–5 business days. Express delivery is available to eligible PIN codes.</p></>}{tab==="Returns"&&<><h2>Easy 30-day returns.</h2><p>Return products in their original condition within 30 days for a full refund.</p></>}</article></section>
  </main>
}

function Wishlist({wishlist,toggleWish,add,openProduct,go}:any){const items=PRODUCTS.filter(p=>wishlist.includes(p.id));return <main className="standard-page"><PageTitle title="Your wishlist" text={`${items.length} saved ${items.length===1?"piece":"pieces"}`}/>{items.length?<div className="section-wrap product-grid">{items.map(p=><ProductCard key={p.id} product={p} {...{openProduct,add,wishlist,toggleWish}}/>)}</div>:<div className="empty-state"><Icon name="heart" size={42}/><h2>Your wishlist is empty</h2><p>Save pieces you love and find them here later.</p><Btn onClick={()=>go("shop")}>Explore products</Btn></div>}</main>}
function Cart({cart,setCart,cartProducts,subtotal,toggleWish,go,notify}:any){
  const [coupon,setCoupon]=useState(""),[couponValue,setCouponValue]=useState(0),[couponError,setCouponError]=useState("")
  const apply=()=>{const codes:Record<string,number>={NOVA10:Math.round(subtotal*.1),SAVE500:500,WELCOME15:Math.round(subtotal*.15)};if(codes[coupon.toUpperCase()]){setCouponValue(codes[coupon.toUpperCase()]);setCouponError("");notify("Coupon applied.")}else{setCouponError("Invalid coupon. Try NOVA10 or SAVE500.");setCouponValue(0)}}
  const remove=(id:number)=>{setCart((c:any)=>{const n={...c};delete n[id];return n});notify("Item removed.","info")}
  return <main className="standard-page cart-page-web"><PageTitle title="Your cart" text={`${cartProducts.length} products · Free delivery unlocked`}/>{cartProducts.length?<div className="cart-layout"><section>{cartProducts.map((p:any)=><article className="cart-row" key={p.id}><img src={p.image}/><div><small>{p.category}</small><h3>{p.name}</h3><span>Midnight Black</span><div className="quantity"><button onClick={()=>p.qty===1?remove(p.id):setCart((c:any)=>({...c,[p.id]:p.qty-1}))}>−</button><b>{p.qty}</b><button onClick={()=>setCart((c:any)=>({...c,[p.id]:p.qty+1}))}>+</button></div><button onClick={()=>{toggleWish(p.id);remove(p.id)}}>Save for later</button><button onClick={()=>remove(p.id)}>Remove</button></div><strong>{money(p.price*p.qty)}</strong></article>)}</section><aside className="order-summary"><h2>Order summary</h2><p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>Delivery</span><b className="green">FREE</b></p><p><span>Taxes</span><b>Included</b></p>{couponValue>0&&<p><span>Coupon discount</span><b className="green">−{money(couponValue)}</b></p>}<div className="coupon"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Coupon code"/><button onClick={apply}>Apply</button></div>{couponError&&<small className="form-error">{couponError}</small>}<hr/><p className="total"><span>Total</span><b>{money(subtotal-couponValue)}</b></p><Btn onClick={()=>go("checkout")}>Secure checkout <Icon name="arrow"/></Btn><Btn kind="text" onClick={()=>go("shop")}>Continue shopping</Btn></aside></div>:<div className="empty-state"><Icon name="bag" size={42}/><h2>Your cart is empty</h2><p>Discover something considered for your everyday.</p><Btn onClick={()=>go("shop")}>Browse products</Btn></div>}</main>
}
function PageTitle({title,text}:{title:string;text:string}){return <div className="page-title"><span>NOVA</span><h1>{title}</h1><p>{text}</p></div>}

function Checkout({cartProducts,subtotal,go,setOrderPlaced,notify}:any){
  const [step,setStep]=useState(1),[address,setAddress]=useState(0),[addressModal,setAddressModal]=useState(false),[delivery,setDelivery]=useState("standard"),[payment,setPayment]=useState("upi"),[error,setError]=useState("")
  const [card,setCard]=useState({number:"",name:"",expiry:"",cvv:""}),[upi,setUpi]=useState("")
  const next=()=>{if(step===3&&payment==="card"&&(card.number.length<16||!card.name||!card.expiry||card.cvv.length<3)){setError("Complete all card details to continue.");return}if(step===3&&payment==="upi"&&!upi.includes("@")){setError("Enter a valid UPI ID.");return}setError("");setStep(Math.min(4,step+1))}
  const place=()=>{setOrderPlaced(true);notify("Order placed successfully.");go("success")}
  if(!cartProducts.length)return <main className="standard-page"><div className="empty-state"><h2>Your cart is empty</h2><Btn onClick={()=>go("shop")}>Shop products</Btn></div></main>
  return <main className="checkout-page"><button className="checkout-logo" onClick={()=>go("home")}><Logo/></button><div className="checkout-progress">{["Address","Delivery","Payment","Review"].map((x,i)=><div className={step>=i+1?"active":""} key={x}><i>{step>i+1?<Icon name="check" size={13}/>:i+1}</i><span>{x}</span></div>)}</div><div className="checkout-layout"><section>
    {step===1&&<><h1>Where should we deliver?</h1><p>Select a saved address or add a new one.</p>{["42, Cedar Heights, Indiranagar, Bengaluru 560038","NOVA Design Studio, Koramangala, Bengaluru 560095"].map((x,i)=><article className={`address-card-web ${address===i?"active":""}`} onClick={()=>setAddress(i)} key={x}><i/><div><strong>Aanya Kapoor <span>{i?"WORK":"HOME"}</span></strong><p>{x}</p><small>+91 98765 43210</small></div><button onClick={e=>{e.stopPropagation();setAddressModal(true)}}>Edit</button></article>)}<Btn kind="secondary" onClick={()=>setAddressModal(true)}>+ Add new address</Btn></>}
    {step===2&&<><h1>Choose delivery speed</h1><p>Your delivery date and total update instantly.</p>{[["standard","Standard delivery","3–5 business days","FREE"],["express","Express delivery","1–2 business days","₹149"]].map(x=><button className={`delivery-choice ${delivery===x[0]?"active":""}`} onClick={()=>setDelivery(x[0])} key={x[0]}><i/><Icon name="truck"/><span><strong>{x[1]}</strong><small>{x[2]}</small></span><b>{x[3]}</b></button>)}</>}
    {step===3&&<><h1>Choose payment</h1><p>All transactions are secure and encrypted.</p><div className="payment-tabs">{[["upi","UPI"],["card","Card"],["net","Net Banking"],["cod","Cash on Delivery"]].map(x=><button className={payment===x[0]?"active":""} onClick={()=>{setPayment(x[0]);setError("")}} key={x[0]}>{x[1]}</button>)}</div>{payment==="upi"&&<Field label="UPI ID" value={upi} onChange={setUpi} placeholder="name@bank"/>}{payment==="card"&&<div className="card-fields"><Field label="Card number" value={card.number} onChange={(v:string)=>setCard({...card,number:v.replace(/\D/g,"").slice(0,16)})} placeholder="1234 5678 9012 3456"/><Field label="Name on card" value={card.name} onChange={(v:string)=>setCard({...card,name:v})}/><Field label="Expiry" value={card.expiry} onChange={(v:string)=>setCard({...card,expiry:v})} placeholder="MM/YY"/><Field label="CVV" value={card.cvv} onChange={(v:string)=>setCard({...card,cvv:v.replace(/\D/g,"").slice(0,3)})} placeholder="•••"/></div>}{payment==="net"&&<select className="field-select"><option>Select your bank</option><option>HDFC Bank</option><option>State Bank of India</option><option>ICICI Bank</option></select>}{payment==="cod"&&<div className="info-box">A ₹40 cash handling fee applies to Cash on Delivery.</div>}{error&&<p className="form-error">{error}</p>}</>}
    {step===4&&<><h1>Review your order</h1><p>Check everything before placing your order.</p>{cartProducts.map((p:any)=><div className="review-line" key={p.id}><img src={p.image}/><span><strong>{p.name}</strong><small>Midnight Black · Qty {p.qty}</small></span><b>{money(p.price*p.qty)}</b></div>)}<div className="review-sections"><button onClick={()=>setStep(1)}><span>DELIVER TO</span><b>Aanya Kapoor · Home</b><em>Edit</em></button><button onClick={()=>setStep(2)}><span>DELIVERY</span><b>{delivery==="express"?"Express · 1–2 days":"Standard · 3–5 days"}</b><em>Edit</em></button><button onClick={()=>setStep(3)}><span>PAYMENT</span><b>{payment.toUpperCase()}</b><em>Edit</em></button></div></>}
    <div className="checkout-controls">{step>1&&<Btn kind="text" onClick={()=>setStep(step-1)}><Icon name="back"/> Back</Btn>}<Btn onClick={step===4?place:next}>{step===4?"Place order":`Continue to ${["","Delivery","Payment","Review"][step]}`} <Icon name="arrow"/></Btn></div>
  </section><aside className="order-summary"><h2>Order summary</h2><p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>Delivery</span><b>{delivery==="express"?"₹149":"FREE"}</b></p><p><span>Tax</span><b>Included</b></p><hr/><p className="total"><span>Total</span><b>{money(subtotal+(delivery==="express"?149:0))}</b></p><div className="secure"><Icon name="check"/>Secure, encrypted checkout</div></aside></div>
  {addressModal&&<Modal title="Add delivery address" close={()=>setAddressModal(false)}><AddressForm close={()=>{setAddressModal(false);notify("Address saved.")}}/></Modal>}</main>
}
function Field({label,value,onChange,placeholder=""}:any){return <label className="field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function AddressForm({close}:any){const [data,setData]=useState({name:"",phone:"",address:"",city:"",state:"",pin:""}),[error,setError]=useState("");const submit=(e:FormEvent)=>{e.preventDefault();if(Object.values(data).some(x=>!x)){setError("Complete all address fields.");return}close()};return <form className="modal-form" onSubmit={submit}>{Object.keys(data).map(k=><Field key={k} label={k[0].toUpperCase()+k.slice(1)} value={(data as any)[k]} onChange={(v:string)=>setData({...data,[k]:v})}/>)}{error&&<p className="form-error">{error}</p>}<div><Btn kind="secondary" onClick={close}>Cancel</Btn><Btn type="submit">Save address</Btn></div></form>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onClick={close}><section className="modal" onClick={e=>e.stopPropagation()}><div><h2>{title}</h2><button onClick={close}><Icon name="close"/></button></div>{children}</section></div>}

function Success({go}:any){return <main className="success-page"><div className="success-icon"><Icon name="check" size={42}/></div><span>ORDER CONFIRMED</span><h1>It’s officially yours.</h1><p>Your order has been received. We’ll let you know as soon as it’s on the way.</p><div className="order-ticket"><span>ORDER NUMBER <b>#NV24061889</b></span><span>EXPECTED DELIVERY <b>Tuesday, 18 June</b></span><div><img src={IMG.headphones}/><strong>NOVA Sound Pro</strong><b>₹4,999</b></div></div><Btn onClick={()=>go("tracking")}>Track your order</Btn><Btn kind="text" onClick={()=>go("home")}>Continue shopping</Btn></main>}
function Tracking({go}:any){const steps=["Order placed","Confirmed","Packed","Shipped","Out for delivery","Delivered"];return <main className="standard-page tracking-page"><PageTitle title="Track order" text="Order #NV24061889 · Arriving Tuesday"/><div className="tracking-layout"><section><div className="tracking-product"><img src={IMG.headphones}/><span><small>NOVA AUDIO</small><strong>NOVA Sound Pro</strong><b>₹4,999</b></span></div><h2>Order journey</h2><div className="timeline">{steps.map((x,i)=><div className={i<3?"done":i===3?"current":""} key={x}><i>{i<3?<Icon name="check" size={13}/>:i+1}</i><span><strong>{x}</strong><small>{i<3?"Completed":i===3?"Expected today":"Pending"}</small></span></div>)}</div></section><aside><span>DELIVERY ADDRESS</span><strong>Aanya Kapoor</strong><p>42, Cedar Heights, Indiranagar<br/>Bengaluru 560038</p><hr/><span>COURIER</span><strong>BlueDart · AWB 5962840182</strong><Btn kind="secondary" onClick={()=>go("support")}>Contact support</Btn></aside></div></main>}

function Account({go,dark,setDark,orderPlaced,loggedIn,setLoggedIn,notify}:any){
  const [tab,setTab]=useState("Overview"),[editing,setEditing]=useState(false)
  if(!loggedIn)return <main className="standard-page"><div className="empty-state"><Icon name="user" size={42}/><h2>Sign in to your account</h2><p>View orders, saved items, addresses, and preferences.</p><Btn onClick={()=>go("auth")}>Sign in</Btn></div></main>
  return <main className="account-page"><aside><div className="profile-mini"><span>AK</span><strong>Aanya Kapoor</strong><small>aanya@example.com</small></div>{["Overview","Orders","Wishlist","Addresses","Payment methods","Notifications","Settings"].map(x=><button className={tab===x?"active":""} onClick={()=>x==="Wishlist"?go("wishlist"):setTab(x)} key={x}>{x}<Icon name="arrow" size={14}/></button>)}<button onClick={()=>{setLoggedIn(false);notify("Logged out successfully.","info");go("home")}}>Log out</button></aside><section>
    <div className="account-head"><div><span>MY ACCOUNT</span><h1>{tab}</h1></div>{tab==="Overview"&&<Btn kind="secondary" onClick={()=>setEditing(!editing)}>{editing?"Save profile":"Edit profile"}</Btn>}</div>
    {tab==="Overview"&&<><div className="stats"><div><b>{orderPlaced?4:3}</b><span>Orders</span></div><div><b>2</b><span>Wishlist</span></div><div><b>3</b><span>Addresses</span></div></div><div className="account-card"><h2>Personal information</h2>{editing?<><Field label="Full name" value="Aanya Kapoor" onChange={()=>{}}/><Field label="Email" value="aanya@example.com" onChange={()=>{}}/></>:<><p><span>Full name</span><b>Aanya Kapoor</b></p><p><span>Email address</span><b>aanya@example.com</b></p><p><span>Phone</span><b>+91 98765 43210</b></p></>}</div></>}
    {tab==="Orders"&&<Orders orderPlaced={orderPlaced} go={go}/>}
    {tab==="Addresses"&&<div className="account-card"><h2>Saved addresses</h2><p><span>HOME</span><b>42, Cedar Heights, Indiranagar, Bengaluru</b></p><Btn kind="secondary" onClick={()=>notify("Address editor opened.","info")}>Add address</Btn></div>}
    {tab==="Payment methods"&&<div className="account-card"><h2>Payment methods</h2><p><span>VISA</span><b>•••• •••• •••• 4242</b></p><Btn kind="secondary" onClick={()=>notify("Payment method added.")}>Add payment method</Btn></div>}
    {tab==="Notifications"&&<div className="account-card"><h2>Notification preferences</h2>{["Order updates","Price drops","Offers and recommendations"].map(x=><Toggle key={x} label={x}/>)}</div>}
    {tab==="Settings"&&<div className="account-card"><h2>Appearance</h2><div className="setting-row"><span><b>Dark theme</b><small>Change the website presentation</small></span><button className={`toggle ${dark?"on":""}`} onClick={()=>setDark(!dark)}><i/></button></div><h2>Region</h2><p><span>Language</span><b>English</b></p><p><span>Currency</span><b>INR · ₹</b></p></div>}
  </section></main>
}
function Toggle({label}:{label:string}){const [on,setOn]=useState(true);return <div className="setting-row"><span><b>{label}</b><small>Email and push notifications</small></span><button className={`toggle ${on?"on":""}`} onClick={()=>setOn(!on)}><i/></button></div>}
function Orders({orderPlaced,go}:any){const [filter,setFilter]=useState("All");return <><div className="order-tabs">{["All","Processing","Shipped","Delivered","Cancelled"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>{(orderPlaced?[1,2]:[2]).map((x,i)=><article className="order-card" key={x}><div><span>ORDER #NV2406188{x}</span><b>{i===0?"Processing":"Delivered"}</b></div><section><img src={IMG.headphones}/><p><strong>NOVA Sound Pro</strong><small>Placed 15 June 2025 · 1 item</small></p><strong>₹4,999</strong></section><footer><Btn kind="secondary" onClick={()=>go("tracking")}>View details</Btn><Btn kind="text" onClick={()=>go("tracking")}>{i===0?"Track order":"Buy again"}</Btn></footer></article>)}</>}

function Support({notify}:any){const [q,setQ]=useState(""),[open,setOpen]=useState(0),[contact,setContact]=useState(false);const faqs=["Where is my order?","How do I return a product?","When will I receive my refund?","Can I change my delivery address?"];return <main className="support-page"><section><span>NOVA SUPPORT</span><h1>How can we help?</h1><div><Icon name="search"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search orders, returns, payments..."/></div></section><div className="section-wrap support-grid"><aside>{["Orders","Payments","Shipping","Returns","Account","Technical help"].map(x=><button onClick={()=>setQ(x)} key={x}>{x}<Icon name="arrow"/></button>)}</aside><article><h2>Frequently asked questions</h2>{faqs.filter(x=>x.toLowerCase().includes(q.toLowerCase())||!q).map((x,i)=><div className="faq" key={x}><button onClick={()=>setOpen(open===i?-1:i)}>{x}<span>{open===i?"−":"+"}</span></button>{open===i&&<p>You can manage this from your NOVA account. Open Orders, select the relevant order, and choose the available action. Our support team can help if you need anything else.</p>}</div>)}<div className="contact-card"><h3>Still need help?</h3><p>Our team usually responds within two hours.</p><Btn onClick={()=>setContact(true)}>Contact support</Btn></div></article></div>{contact&&<Modal title="Contact NOVA support" close={()=>setContact(false)}><SupportForm close={()=>{setContact(false);notify("Your request has been submitted.")}}/></Modal>}</main>}
function SupportForm({close}:any){const [data,setData]=useState({name:"",email:"",subject:"",message:""}),[error,setError]=useState("");const submit=(e:FormEvent)=>{e.preventDefault();if(Object.values(data).some(x=>!x)){setError("Complete every field before submitting.");return}close()};return <form className="modal-form" onSubmit={submit}>{Object.keys(data).map(k=><Field key={k} label={k} value={(data as any)[k]} onChange={(v:string)=>setData({...data,[k]:v})}/>)}{error&&<p className="form-error">{error}</p>}<div><Btn kind="secondary" onClick={close}>Cancel</Btn><Btn type="submit">Submit request</Btn></div></form>}

function ReviewCenter({direction,setDirection,notify,go,add}:any){
  const [view,setView]=useState("Dashboard"),[reviewScreen,setReviewScreen]=useState("Home"),[vote,setVote]=useState<Direction|null>(null),[reasons,setReasons]=useState<string[]>([]),[comment,setComment]=useState(""),[approved,setApproved]=useState<Direction|null>(null),[change,setChange]=useState(false)
  const tabs=["Dashboard","Compare","Feedback","Decision matrix","Approval","Handoff"]
  return <main className="review-center"><aside><Logo/><span>DESIGN REVIEW CENTER</span>{tabs.map(x=><button className={view===x?"active":""} onClick={()=>setView(x)} key={x}>{x}<Icon name="arrow" size={14}/></button>)}<Btn kind="secondary" onClick={()=>go("home")}>Back to store</Btn></aside><section>
    <div className="review-top"><span>NOVA E-COMMERCE UI · V1.0</span><h1>{view}</h1><p>Evaluate controlled design alternatives and align on a direction with clear evidence.</p></div>
    {view==="Dashboard"&&<><div className="review-problem"><div><span>PROBLEM</span><h2>Stakeholders have conflicting interface priorities.</h2></div><div><span>OBJECTIVE</span><h2>Select a direction through interactive evaluation.</h2></div></div><DirectionCards select={(d:Direction)=>{setDirection(d);setView("Compare")}}/><Btn onClick={()=>setView("Compare")}>Start stakeholder review <Icon name="arrow"/></Btn></>}
    {view==="Compare"&&<><div className="screen-select">{["Home","Listing","Product detail","Checkout"].map(x=><button className={reviewScreen===x?"active":""} onClick={()=>setReviewScreen(x)} key={x}>{x}</button>)}</div><DirectionCards select={(d:Direction)=>{setDirection(d);if(reviewScreen==="Checkout")add(1);go(reviewScreen==="Home"?"home":reviewScreen==="Listing"?"shop":reviewScreen==="Product detail"?"product":"checkout")}}/><div className="comparison-table"><div><b>Criteria</b><b>A · Minimal</b><b>B · Commerce</b><b>C · Premium</b></div>{[["Main focus","Simplicity","Conversion","Brand"],["Promo density","Low","High","Medium"],["Strength","Easy to scan","Discovery","Visual identity"],["Trade-off","May feel sparse","Can feel busy","Slower scanning"]].map(r=><div key={r[0]}>{r.map(x=><span key={x}>{x}</span>)}</div>)}</div><Btn onClick={()=>setView("Feedback")}>Continue to feedback</Btn></>}
    {view==="Feedback"&&<div className="feedback-form"><span>WHICH DESIGN DO YOU PREFER?</span><div className="vote-buttons">{(["A","B","C"] as Direction[]).map(d=><button className={vote===d?"active":""} onClick={()=>setVote(d)} key={d}><b>{d}</b>{d==="A"?"Minimal":d==="B"?"Commerce":"Premium"}</button>)}</div><span>WHAT INFLUENCED YOUR CHOICE?</span><div className="reason-buttons">{["Easier to use","More attractive","Better discovery","More trustworthy","Better branding","Less cluttered","Faster to understand"].map(x=><button className={reasons.includes(x)?"active":""} onClick={()=>setReasons(r=>r.includes(x)?r.filter(y=>y!==x):[...r,x])} key={x}>{reasons.includes(x)&&<Icon name="check" size={13}/>} {x}</button>)}</div><label>Additional comments<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Share observations or concerns..."/></label><Btn disabled={!vote} onClick={()=>{notify("Feedback submitted.");setView("Decision matrix")}}>Submit feedback</Btn></div>}
    {view==="Decision matrix"&&<><div className="matrix-web"><div><b>Criteria</b><b>A</b><b>B</b><b>C</b></div>{[["Usability",5,4,4],["Visual appeal",3,4,5],["Product discovery",3,5,4],["Conversion potential",3,5,4],["Brand perception",3,4,5],["Accessibility",5,4,4],["Navigation simplicity",5,4,4]].map(r=><div key={r[0]}>{r.map((x,i)=><span key={i}>{i?`${"●".repeat(Number(x))}${"○".repeat(5-Number(x))}`:x}</span>)}</div>)}<div className="matrix-total"><b>Weighted score</b><b>27</b><b>30</b><b>30</b></div></div><div className="feedback-summary"><h2>Aggregate feedback</h2><div><span><b>28%</b>Direction A</span><span><b>47%</b>Direction B</span><span><b>25%</b>Direction C</span></div><p>Most common themes: better product discovery, cleaner navigation, stronger visual identity.</p></div><Btn onClick={()=>setView("Approval")}>Proceed to approval</Btn></>}
    {view==="Approval"&&<div className="approval-box">{approved?<><div className="approved-mark"><Icon name="check" size={34}/></div><span>DESIGN APPROVED</span><h2>Direction {approved} · {approved==="A"?"Minimal":approved==="B"?"Commerce":"Premium"}</h2><p>Approved 18 June 2025 · Home, listing, product detail, cart, and checkout.</p><div className="next-handoff"><span>NEXT STEP</span><strong>Proceed to Development Handoff</strong><Btn onClick={()=>setView("Handoff")}>Open handoff</Btn></div></>:<><span>RECOMMENDED DIRECTION</span><h2>Direction B · Commerce-first</h2><p>Strong product discovery and conversion while maintaining clear, usable navigation.</p><div className="approval-choices">{(["A","B","C"] as Direction[]).map(d=><button onClick={()=>setApproved(d)} key={d}>Approve Direction {d}</button>)}<button onClick={()=>setChange(true)}>Request changes</button></div></>}</div>}
    {view==="Handoff"&&<Handoff/>}
  </section>{change&&<Modal title="Request design changes" close={()=>setChange(false)}><SupportForm close={()=>{setChange(false);notify("Change request recorded.")}}/></Modal>}</main>
}
function DirectionCards({select}:any){return <div className="direction-cards">{(["A","B","C"] as Direction[]).map(d=><article key={d}><div className={`direction-preview p${d}`}><i/><i/><div><b/><b/></div></div><span>DIRECTION {d}</span><h2>{d==="A"?"Minimal":d==="B"?"Commerce-first":"Premium"}</h2><p>{d==="A"?"Quiet, clear, and frictionless.":d==="B"?"Active discovery and conversion.":"Editorial, immersive, differentiated."}</p><dl><div><dt>Strength</dt><dd>{d==="A"?"Usability":d==="B"?"Discovery":"Brand affinity"}</dd></div><div><dt>Trade-off</dt><dd>{d==="A"?"Fewer sales cues":d==="B"?"More density":"Less scannable"}</dd></div></dl><Btn kind={d==="B"?"primary":"secondary"} onClick={()=>select(d)}>Experience direction {d}</Btn></article>)}</div>}
function Handoff(){return <div className="handoff"><section><span>COLOR TOKENS</span><div className="swatches-handoff"><i/><i/><i/><i/><i/></div></section><section><span>TYPOGRAPHY</span><h2>Display / Manrope 700</h2><p>Body / DM Sans 400 · Clear, practical, and highly readable.</p></section><section><span>SPACING</span><div className="spacing-demo"><i/><i/><i/><i/><i/></div></section><section><span>CORE COMPONENTS</span><div><Btn>Primary button</Btn><Btn kind="secondary">Secondary button</Btn><input placeholder="Form input"/></div></section><section><span>RESPONSIVE RULES</span><p>Desktop: 12-column content grid · Tablet: 8 columns · Mobile: 4 columns with 16px page margins. Minimum interactive target: 44px.</p></section></div>}

function Auth({setLoggedIn,go,notify}:any){const [mode,setMode]=useState("login"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();if(mode==="forgot"){if(!email.includes("@")){setError("Enter a valid email address.");return}setDone(true);return}if(mode==="register"&&!name.trim()){setError("Enter your full name.");return}if(!email.includes("@")||password.length<6){setError("Enter a valid email and a password of at least 6 characters.");return}if(mode==="register"&&password.length<8){setError("Use at least 8 characters for your password.");return}setLoggedIn(true);notify(mode==="register"?"Account created successfully.":"Welcome back, Aanya.");go("home")};return <main className="auth-page"><section><button onClick={()=>go("home")}><Logo/></button><span>EVERYTHING YOU WANT. ONE PLACE.</span><h1>{mode==="login"?"Welcome back.":mode==="register"?"Join NOVA.":"Reset your password."}</h1><p>{mode==="login"?"Sign in to access your orders, wishlist, and personalized edit.":mode==="register"?"Create an account for a more considered shopping experience.":"We’ll send a secure reset link to your email."}</p></section><form onSubmit={submit}>{done?<div className="auth-success"><Icon name="check" size={35}/><h2>Check your inbox</h2><p>A password reset link has been sent to {email}.</p><Btn onClick={()=>{setDone(false);setMode("login")}}>Back to login</Btn></div>:<><h2>{mode==="login"?"Sign in":mode==="register"?"Create account":"Forgot password"}</h2>{mode==="register"&&<Field label="Full name" value={name} onChange={setName} placeholder="Aanya Kapoor"/>}<Field label="Email" value={email} onChange={setEmail} placeholder="you@example.com"/>{mode!=="forgot"&&<label className="field password"><span>Password</span><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/><button type="button" onClick={()=>setShow(!show)}><Icon name="eye"/></button></label>}{error&&<p className="form-error">{error}</p>}<Btn type="submit">{mode==="login"?"Sign in":mode==="register"?"Create account":"Send reset link"}</Btn>{mode==="login"&&<><button type="button" className="auth-link" onClick={()=>{setMode("forgot");setError("")}}>Forgot password?</button><Btn kind="secondary" onClick={()=>{setLoggedIn(false);go("home");notify("Continuing as guest.","info")}}>Continue as guest</Btn></>}<p className="auth-switch">{mode==="register"?"Already have an account?":"New to NOVA?"} <button type="button" onClick={()=>{setMode(mode==="register"?"login":"register");setError("")}}>{mode==="register"?"Sign in":"Create account"}</button></p></>}</form></main>}

function SearchOverlay({query,setQuery,search,setSearchOpen,openProduct}:any){const matches=PRODUCTS.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase())).slice(0,4);return <div className="search-overlay"><div><form onSubmit={e=>{e.preventDefault();search()}}><Icon name="search"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search NOVA"/><button type="button" onClick={()=>setSearchOpen(false)}><Icon name="close"/></button></form><section><span>{query?"SUGGESTIONS":"POPULAR SEARCHES"}</span>{query?matches.map((p:any)=><button key={p.id} onClick={()=>{setSearchOpen(false);openProduct(p)}}><img src={p.image}/><b>{p.name}</b><small>{p.category}</small><Icon name="arrow"/></button>):["wireless headphones","everyday sneakers","skin care kit","coffee maker"].map((x:string)=><button key={x} onClick={()=>search(x)}><Icon name="search"/><b>{x}</b><Icon name="arrow"/></button>)}</section></div></div>}
function Footer({go,notify}:any){const [email,setEmail]=useState(""),[subscribed,setSubscribed]=useState(false);const sub=(e:FormEvent)=>{e.preventDefault();if(!email.includes("@")){notify("Enter a valid email address.","error");return}setSubscribed(true)};return <footer className="nova-footer"><div className="footer-brand"><Logo/><p>Everything you want. One place.</p><form onSubmit={sub}>{subscribed?<strong>You're subscribed to NOVA updates.</strong>:<><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address"/><button>Subscribe</button></>}</form></div>{[["Shop",["Electronics","Fashion","Beauty","Home","Sports"]],["Customer service",["Help center","Contact us","Shipping","Returns"]],["Company",["About NOVA","Careers","Privacy","Terms"]]].map(col=><div key={col[0] as string}><strong>{col[0]}</strong>{(col[1] as string[]).map(x=><button key={x} onClick={()=>x.match(/Help|Contact|Shipping|Returns/)?go("support"):x.match(/Electronics|Fashion|Beauty|Home|Sports/)?go("shop"):notify(`${x} information opened.`,"info")}>{x}</button>)}</div>)}<div className="footer-bottom"><span>© 2025 NOVA Commerce Private Limited</span><span>India · INR · Accessibility</span><div>{["in","f","x"].map(x=><button onClick={()=>notify(`NOVA on ${x} opened.`,"info")} key={x}>{x}</button>)}</div></div></footer>}
